/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as incrementSol from "./Increment.sol";
export type { incrementSol };
export type { Lock } from "./Lock";
