/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as incrementSol from "./Increment.sol";
export type { incrementSol };
export type { Election } from "./Election";
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { Election__factory } from "./factories/Election__factory";
export type { Incrementer } from "./Increment.sol/Incrementer";
export { Incrementer__factory } from "./factories/Increment.sol/Incrementer__factory";
export { Lock__factory } from "./factories/Lock__factory";
