/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as incrementSol from "./Increment.sol";
export type { incrementSol };
import type * as deprecated from "./deprecated";
export type { deprecated };
export type { Election } from "./Election";
export type { Lock } from "./Lock";
export * as factories from "./factories";
export type { Incrementer } from "./deprecated/Increment.sol/Incrementer";
export { Incrementer__factory } from "./factories/deprecated/Increment.sol/Incrementer__factory";
export type { Lock } from "./deprecated/Lock";
export { Lock__factory } from "./factories/deprecated/Lock__factory";
export { Election__factory } from "./factories/Election__factory";
